FROM ubuntu:20.04

ARG zookeeper_connect
ARG scala_version=2.12
ARG kafka_version=2.7.0
ARG kafka_tgz_file=kafka_${scala_version}-${kafka_version}.tgz
ARG kafka_untar_folder=kafka_${scala_version}-${kafka_version}
ARG kafka_folder=kafka-${scala_version}-${kafka_version}
ARG kafka_url=https://muug.ca/mirror/apache-dist/kafka/${kafka_version}/${kafka_tgz_file}

# install dependencies
RUN apt-get update -y
RUN apt-get install vim -y
RUN apt-get install wget -y
RUN apt-get install openjdk-8-jdk -y 

WORKDIR /opt/

# install apache kafka
RUN wget ${kafka_url}
RUN tar -xvzf ./${kafka_tgz_file}
RUN cp -r ./${kafka_untar_folder} ./${kafka_folder}
RUN rm -rf ./${kafka_untar_folder}
RUN export PATH=${PATH}:/opt/${kafka_folder}/bin
COPY ./server.properties ./${kafka_folder}/config/

RUN echo "zookeeper.connect=${zookeeper_connect}" >> ./${kafka_folder}/config/server.properties

# start kafka broker
WORKDIR /opt/${kafka_folder}
CMD ["bin/kafka-server-start.sh","config/server.properties"]





